export const Add_To_CART="ADD_TO_CART";
export const VIEW_ITEM="VIEW_ITEM";

export const UPDATE_QTY="UPDATE_QTY";
export const REMOVE_ITEM="REMOVE_ITEM";

export const ADD_FAVOURITES="ADD_FAVOURITES";
// export const REMOVE_FAVOURITES="REMOVE_FAVOURITES";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";

export const SEARCH="SEARCH";

